### PR TITLE
Update PowerSave.ino Final Proposition

### PR DESCRIPTION
**Pull request by NaKroTeK**
Final proposition for fix with PowerSave example (Sorry For 1st PR, was not on Workstation)
No more '0' option, either you wake up the chip or you don't.

### CODE REVIEW

**Comment by smkkHw** [comment]
Ciao Pierre.

Thank for the support on this library.
I agree on the changes on the sketch SfxDownlink.ino that correctly initialize the LED befre starts.

But could U please tell me why should we remove the 0 item from the menu of the PowerSave setch ?

The intention of the example is to show to the user that if he does not wake up the component before send the message that one is not sent to SFX Network and exit from timeout.
If, correctly, move the component out of the sleep the message will be sent and he has the OK answer.

Mik

**Comment by NaKroTeK** [comment]
Hi Mik,

Maybe I misunderstood the example then, I did not understand (maybe a long
long day).
With your insight, indeed there is no interest to remove 0 from the menu.

Small Question BTW, does the modem remember his "sleeping state" when
powered off & back on ?

Thanks Mik
& your welcome for the small typo. (I think there is one too in the
SfxDownlink too)

BR
Alex.

_PIERRE Alexandre_

2016-04-05 20:56 GMT+02:00 MikHw notifications@github.com:

**Comment by smkkHw** [comment]
Yes Alex.
When configured the powerSave is persistence into Telit chip.

To remove it it is necessary to run the example again with the new status SFX_NO_WAKE.

I will update the example because it is not clear.

**Comment by smkkHw** [comment]
Please run a new pull request with only SfxDownlink.ino.
And I will accept

**Pull request closed without merging**
